# Generated by Django 4.0.1 on 2022-01-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='name',
        ),
    ]
