# Generated by Django 4.0.1 on 2022-01-22 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_guest_name_alter_name_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
