# Generated by Django 4.0.1 on 2022-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='AccNo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='holder',
            field=models.TextField(blank=True, null=True),
        ),
    ]
